### ISSUE TITLE
fix directory permissions error

### ISSUE THREAD

**Issue by nathandunn** [erasche/docker-compose-galaxy-annotation#3]
On load we had directory permission errors after I applied this patch (was giving a space error before it):

https://github.com/TAMU-CPT/galaxy-webapollo/pull/3

```
cp -R /export/galaxy-central/database/files/000/dataset_5_files/data/ /apollo-data/5; python /galaxy-central/tools/apollo/add_organism.py $GALAXY_WEBAPOLLO_URL galaxy@gmod.org $GALAXY_WEBAPOLLO_PASSWORD --genus "" --species "" --public "Volvox Sample Animal" "/apollo-data/5" admin@galaxy.org > /export/galaxy-central/database/files/000/dataset_40.dat
```

Error is . . (I get the same error after running register user as well):

```
Fatal error: Exit code 1 ()
cp: cannot create directory ‘/apollo-data/5’: Permission denied
Traceback (most recent call last):
  File "/galaxy-central/tools/apollo/add_organism.py", line 32, in <module>
    raise Exception("Unknown user. Please register first")
Exception: Unknown user. Please register first
```

Permissions are:

    drwxr-xr-x   1   1000 staff    68 May 18 21:08 apollo-data

    chmod -R 777 /apollo-data   

yields the same permissions

chmod -R 777 data  (local, not in the docker image) does nothing.   

Not sure where data is stored (not in those directories).

**Comment by erasche** [comment]
This *should* have been covered by https://github.com/erasche/docker-galaxy-annotation/blob/24ba62981c4b35ae403f9e36b30cf5357fb69ffa/postinst.sh#L6

but I am guessing something strange happens due to you mounting it from a host folder.

Would you mind testing without the mounted folder? I.e.

- Remove https://github.com/erasche/docker-compose-galaxy-annotation/blob/master/docker-compose.yml#L22
- docker-compose kill / rm -f / up

**Comment by erasche** [comment]
Seems to be fixed by removing volume mount.

**Comment by nathandunn** [comment]
agreed
